
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbcqdfytbadrssxigdqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiY3FkZnl0YmFkcnNzeGlnZHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMDA3NDYsImV4cCI6MjA1Njc3Njc0Nn0.PN9A3oHJGPUOO7AijLenI4Iz6kbECpNu05B6rl1CC98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
